services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - type: bind
        source: /tmp/.X11-unix/
        target: /tmp/.X11-unix
      - type: bind
        source: ./app
        target: /app
    env_file:
      - .env
    ports:
      - "127.0.0.1:1420:1420"
